### ISSUE TITLE
Change recipe name

### ISSUE THREAD

**Issue by JoeBerkley** [EtchUK/Etch.OrchardCore.Widgets#29]
Currently the recipe name is pretty generic, and as Orchard doesn't like multiple recipes with the same name, its possible this could cause collision with something else

**Comment by peterkeating** [comment]
Ace, can you also submit a PR on the host theme to correct the name here - https://github.com/EtchUK/Etch.OrchardCore.HostTheme/blob/master/Recipes/setup.recipe.json#L566
