### ISSUE TITLE
ID is assigned in section but never used

### ISSUE THREAD

**Issue by Newnab** [EtchUK/Etch.OrchardCore.Widgets#48]
https://github.com/EtchUK/Etch.OrchardCore.Widgets/blob/968a7eba2f9e34db3d7f1ab5d44568e0cb80c992/Views/Widget-Section.liquid#L1

I imagine we want to output this with `id={{ id }}` on the <section> element by default.

**Comment by peterkeating** [comment]
Resolved via https://github.com/EtchUK/Etch.OrchardCore.Widgets/pull/47/commits/16b7ffdaa51c6ca14c4e0f47a1365f49ab2a882f.
